### ISSUE TITLE
关于_sample_goal 中 random_integers，还有 _select_option 中的 randint 问题

### ISSUE THREAD

**Issue by PeiZhangNEU** [IanYangChina/UOF-paper-code#1]
multigoal_fetch_env.py 中
def _sample_goal(self):
        '''
        这个貌似有点问题，用ind只可能返回0，1，永远得不到最难的那个subgoal作为desired goal啊
        '''
        # this function will return a final goal
        ind = self.np_random.random_integers(0, len(self.final_goal_space))  # random_integers 在gym中 = randint，左闭右开区间
        goal_str = self.final_goal_strs[ind]
        return goal_str
 
universal_option_framework.py 中
def _select_option(self, state, high_level_goal, desired_goal_id, ep=0, test=False):
      。。。
        else:
            if self.env.np_random.uniform(0, 1) < self.optor_exploration(ep):
                
                # 这个貌似有点问题，用ind只可能返回0，1，永远得不到最难的那个subgoal作为desired goal啊
                option = self.env.np_random.randint(0, self.option_num-1)  
            else:
                option = T.argmax(option_values).item()
        return option

**Comment by IanYangChina** [comment]
Thanks for raising up the issue! I have fixed the bug. Yes you are right, it should be `(0, self.option_num)`. However, because I used abstract demonstrations in the experiment, this bug shouldn't have affected much of the result, since the agent's exploration was guided by demonstrations largely anyway....

**Comment by PeiZhangNEU** [comment]
you are welcome! 作者的论文和代码写的都很精彩！敬礼
